// ============================
// Mock Data for Demo Mode
// ============================

// Helper: date string N days from now
const daysFromNow = (days) => {
    const d = new Date();
    d.setDate(d.getDate() + days);
    return d.toISOString().split('T')[0];
};

const pastDate = (daysAgo) => {
    const d = new Date();
    d.setDate(d.getDate() - daysAgo);
    return d.toISOString().split('T')[0];
};

// ===== FUERZAS =====
export const FUERZAS = [
    { id: 1, nombre: 'Ejército Argentino', codigo: 'EA' },
    { id: 2, nombre: 'Armada Argentina', codigo: 'ARA' },
    { id: 3, nombre: 'Fuerza Aérea Argentina', codigo: 'FAA' },
];

// ===== GRADOS =====
export const GRADOS = [
    // EA - Oficiales
    { id: 1, nombre: 'General de Brigada', abreviatura: 'Grl Br', codigoOTAN: 'OF-6', tipo: 'Oficial', fuerzaId: 1 },
    { id: 2, nombre: 'Coronel', abreviatura: 'Cnl', codigoOTAN: 'OF-5', tipo: 'Oficial', fuerzaId: 1 },
    { id: 3, nombre: 'Teniente Coronel', abreviatura: 'Tcnl', codigoOTAN: 'OF-4', tipo: 'Oficial', fuerzaId: 1 },
    // EA - Suboficiales
    { id: 4, nombre: 'Suboficial Mayor', abreviatura: 'SM', codigoOTAN: 'OR-9', tipo: 'Suboficial', fuerzaId: 1 },
    { id: 5, nombre: 'Suboficial Principal', abreviatura: 'SP', codigoOTAN: 'OR-8', tipo: 'Suboficial', fuerzaId: 1 },
    // ARA - Oficiales
    { id: 6, nombre: 'Capitán de Navío', abreviatura: 'CPNV', codigoOTAN: 'OF-5', tipo: 'Oficial', fuerzaId: 2 },
    { id: 7, nombre: 'Capitán de Fragata', abreviatura: 'CPFG', codigoOTAN: 'OF-4', tipo: 'Oficial', fuerzaId: 2 },
    // ARA - Suboficiales
    { id: 8, nombre: 'Suboficial Mayor', abreviatura: 'SMAY', codigoOTAN: 'OR-9', tipo: 'Suboficial', fuerzaId: 2 },
    // FAA - Oficiales
    { id: 9, nombre: 'Comodoro', abreviatura: 'Com', codigoOTAN: 'OF-5', tipo: 'Oficial', fuerzaId: 3 },
    { id: 10, nombre: 'Vicecomodoro', abreviatura: 'Vcom', codigoOTAN: 'OF-4', tipo: 'Oficial', fuerzaId: 3 },
    // FAA - Suboficiales
    { id: 11, nombre: 'Suboficial Mayor', abreviatura: 'SM', codigoOTAN: 'OR-9', tipo: 'Suboficial', fuerzaId: 3 },
];

// ===== PAISES =====
export const PAISES = [
    { id: 1, nombre: 'Estados Unidos', codigoISO: 'US' },
    { id: 2, nombre: 'Brasil', codigoISO: 'BR' },
    { id: 3, nombre: 'Chile', codigoISO: 'CL' },
    { id: 4, nombre: 'Alemania', codigoISO: 'DE' },
    { id: 5, nombre: 'España', codigoISO: 'ES' },
    { id: 6, nombre: 'Israel', codigoISO: 'IL' },
    { id: 7, nombre: 'Francia', codigoISO: 'FR' },
    { id: 8, nombre: 'China', codigoISO: 'CN' },
    { id: 9, nombre: 'Italia', codigoISO: 'IT' },
    { id: 10, nombre: 'Perú', codigoISO: 'PE' },
    { id: 11, nombre: 'Colombia', codigoISO: 'CO' },
    { id: 12, nombre: 'Reino Unido', codigoISO: 'GB' },
    { id: 13, nombre: 'Rusia', codigoISO: 'RU' },
    { id: 14, nombre: 'Paraguay', codigoISO: 'PY' },
    { id: 15, nombre: 'Bolivia', codigoISO: 'BO' },
    { id: 16, nombre: 'Uruguay', codigoISO: 'UY' },
];

// ===== CARGOS =====
export const CARGOS = [
    { valor: 'Agregado de Defensa', tipo: 'Oficial', nivel: 'Directivo' },
    { valor: 'Agregado Militar', tipo: 'Oficial', nivel: 'Directivo' },
    { valor: 'Agregado Naval', tipo: 'Oficial', nivel: 'Directivo' },
    { valor: 'Agregado Aeronáutico', tipo: 'Oficial', nivel: 'Directivo' },
    { valor: 'Adjunto Militar', tipo: 'Oficial', nivel: 'Directivo' },
    { valor: 'Auxiliar de Agregaduría', tipo: 'Suboficial', nivel: 'Operativo' },
    { valor: 'Asistente Administrativo', tipo: 'Suboficial', nivel: 'Operativo' },
];

// ===== AGREGADURIAS (main data) =====
export const AGREGADURIAS = [
    {
        id: 1,
        pais: 'Estados Unidos', paisId: 1,
        fuerza: 'Ejército Argentino', fuerzaCodigo: 'EA', fuerzaId: 1,
        grado: 'Coronel', gradoAbreviatura: 'Cnl', gradoId: 2,
        cargo: 'Agregado Militar',
        apellidoNombre: 'BRUSA, José Alberto',
        fechaSalida: pastDate(540),
        finComision: daysFromNow(280),
        telefonoOficial: '(001-202) 555-1234',
        direccionOficial: '1600 New Hampshire Ave NW, Washington DC',
        correoElectronico: 'jbrusa@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'DEC-2024/0128',
        firmaDecretoResol: pastDate(560),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: null,
        diasRestantes: 280,
    },
    {
        id: 2,
        pais: 'Brasil', paisId: 2,
        fuerza: 'Ejército Argentino', fuerzaCodigo: 'EA', fuerzaId: 1,
        grado: 'Teniente Coronel', gradoAbreviatura: 'Tcnl', gradoId: 3,
        cargo: 'Agregado Militar',
        apellidoNombre: 'RODRIGUEZ, Martín Alejandro',
        fechaSalida: pastDate(400),
        finComision: daysFromNow(45),
        telefonoOficial: '(0055-61) 3443-5500',
        direccionOficial: 'SES Av. das Nações Q807 Lote 14, Brasilia',
        correoElectronico: 'mrodriguez@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'DEC-2024/0095',
        firmaDecretoResol: pastDate(420),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: 'Pendiente designación',
        diasRestantes: 45,
    },
    {
        id: 3,
        pais: 'Chile', paisId: 3,
        fuerza: 'Ejército Argentino', fuerzaCodigo: 'EA', fuerzaId: 1,
        grado: 'Coronel', gradoAbreviatura: 'Cnl', gradoId: 2,
        cargo: 'Agregado de Defensa',
        apellidoNombre: 'FERNÁNDEZ, Carlos Eduardo',
        fechaSalida: pastDate(300),
        finComision: daysFromNow(420),
        telefonoOficial: '(0056-2) 2582-8830',
        direccionOficial: 'Av. Vicuña Mackenna 351, Santiago',
        correoElectronico: 'cfernandez@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'DEC-2025/0034',
        firmaDecretoResol: pastDate(320),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: null,
        diasRestantes: 420,
    },
    {
        id: 4,
        pais: 'Alemania', paisId: 4,
        fuerza: 'Ejército Argentino', fuerzaCodigo: 'EA', fuerzaId: 1,
        grado: 'Coronel', gradoAbreviatura: 'Cnl', gradoId: 2,
        cargo: 'Agregado de Defensa',
        apellidoNombre: 'LÓPEZ, Miguel Ángel',
        fechaSalida: pastDate(600),
        finComision: daysFromNow(15),
        telefonoOficial: '(00-49-030) 2266-8941',
        direccionOficial: 'Von-der-Heydt-Strabe 2, 10785 Berlin',
        correoElectronico: 'mlopez@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'DEC-2023/0211',
        firmaDecretoResol: pastDate(620),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: 'Tcnl MÉNDEZ, R.',
        diasRestantes: 15,
    },
    {
        id: 5,
        pais: 'España', paisId: 5,
        fuerza: 'Armada Argentina', fuerzaCodigo: 'ARA', fuerzaId: 2,
        grado: 'Capitán de Navío', gradoAbreviatura: 'CPNV', gradoId: 6,
        cargo: 'Agregado Naval',
        apellidoNombre: 'MARTÍNEZ, Luis Hernán',
        fechaSalida: pastDate(350),
        finComision: daysFromNow(370),
        telefonoOficial: '(0034-91) 771-2600',
        direccionOficial: 'Calle Jorge Juan 9, 28001 Madrid',
        correoElectronico: 'lmartinez@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'DEC-2025/0012',
        firmaDecretoResol: pastDate(370),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: null,
        diasRestantes: 370,
    },
    {
        id: 6,
        pais: 'Israel', paisId: 6,
        fuerza: 'Armada Argentina', fuerzaCodigo: 'ARA', fuerzaId: 2,
        grado: 'Capitán de Fragata', gradoAbreviatura: 'CPFG', gradoId: 7,
        cargo: 'Agregado Naval',
        apellidoNombre: 'SÁNCHEZ, Pablo Diego',
        fechaSalida: pastDate(250),
        finComision: daysFromNow(480),
        telefonoOficial: '(00-972-3) 544-5200',
        direccionOficial: 'Derech Menachem Begin 85, Tel Aviv',
        correoElectronico: 'psanchez@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'DEC-2025/0067',
        firmaDecretoResol: pastDate(270),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: null,
        diasRestantes: 480,
    },
    {
        id: 7,
        pais: 'Francia', paisId: 7,
        fuerza: 'Fuerza Aérea Argentina', fuerzaCodigo: 'FAA', fuerzaId: 3,
        grado: 'Comodoro', gradoAbreviatura: 'Com', gradoId: 9,
        cargo: 'Agregado Aeronáutico',
        apellidoNombre: 'GUTIÉRREZ, Ricardo Omar',
        fechaSalida: pastDate(450),
        finComision: daysFromNow(190),
        telefonoOficial: '(0033-1) 4431-3300',
        direccionOficial: '6 Rue Cimarosa, 75116 Paris',
        correoElectronico: 'rgutierrez@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'DEC-2024/0156',
        firmaDecretoResol: pastDate(470),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: null,
        diasRestantes: 190,
    },
    {
        id: 8,
        pais: 'China', paisId: 8,
        fuerza: 'Fuerza Aérea Argentina', fuerzaCodigo: 'FAA', fuerzaId: 3,
        grado: 'Vicecomodoro', gradoAbreviatura: 'Vcom', gradoId: 10,
        cargo: 'Adjunto Militar',
        apellidoNombre: 'ACOSTA, Federico Andrés',
        fechaSalida: pastDate(200),
        finComision: daysFromNow(520),
        telefonoOficial: '(0086-10) 6532-1990',
        direccionOficial: 'Dongzhimenwai Dajie 11, Beijing',
        correoElectronico: 'facosta@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'DEC-2025/0089',
        firmaDecretoResol: pastDate(220),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: null,
        diasRestantes: 520,
    },
    {
        id: 9,
        pais: 'Italia', paisId: 9,
        fuerza: 'Ejército Argentino', fuerzaCodigo: 'EA', fuerzaId: 1,
        grado: 'Teniente Coronel', gradoAbreviatura: 'Tcnl', gradoId: 3,
        cargo: 'Adjunto Militar',
        apellidoNombre: 'DI MARCO, Alessandro',
        fechaSalida: pastDate(500),
        finComision: daysFromNow(55),
        telefonoOficial: '(0039-06) 4884-2841',
        direccionOficial: 'Piazza dell\'Esquilino 2, Roma',
        correoElectronico: 'adimarco@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'DEC-2024/0042',
        firmaDecretoResol: pastDate(520),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: 'Pendiente designación',
        diasRestantes: 55,
    },
    {
        id: 10,
        pais: 'Perú', paisId: 10,
        fuerza: 'Armada Argentina', fuerzaCodigo: 'ARA', fuerzaId: 2,
        grado: 'Capitán de Fragata', gradoAbreviatura: 'CPFG', gradoId: 7,
        cargo: 'Agregado Naval',
        apellidoNombre: 'TORRES, Juan Manuel',
        fechaSalida: pastDate(180),
        finComision: daysFromNow(550),
        telefonoOficial: '(0051-1) 433-3381',
        direccionOficial: 'Av. Javier Prado Oeste 995, Lima',
        correoElectronico: 'jtorres@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'DEC-2025/0102',
        firmaDecretoResol: pastDate(200),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: null,
        diasRestantes: 550,
    },
    {
        id: 11,
        pais: 'Colombia', paisId: 11,
        fuerza: 'Fuerza Aérea Argentina', fuerzaCodigo: 'FAA', fuerzaId: 3,
        grado: 'Vicecomodoro', gradoAbreviatura: 'Vcom', gradoId: 10,
        cargo: 'Agregado Aeronáutico',
        apellidoNombre: 'HERRERA, Diego Sebastián',
        fechaSalida: pastDate(320),
        finComision: daysFromNow(400),
        telefonoOficial: '(0057-1) 288-7800',
        direccionOficial: 'Carrera 9 No. 94A-37, Bogotá',
        correoElectronico: 'dherrera@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'DEC-2025/0018',
        firmaDecretoResol: pastDate(340),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: null,
        diasRestantes: 400,
    },
    {
        id: 12,
        pais: 'Estados Unidos', paisId: 1,
        fuerza: 'Ejército Argentino', fuerzaCodigo: 'EA', fuerzaId: 1,
        grado: 'Suboficial Mayor', gradoAbreviatura: 'SM', gradoId: 4,
        cargo: 'Auxiliar de Agregaduría',
        apellidoNombre: 'GÓMEZ, Roberto Daniel',
        fechaSalida: pastDate(530),
        finComision: daysFromNow(290),
        telefonoOficial: '(001-202) 555-1235',
        direccionOficial: '1600 New Hampshire Ave NW, Washington DC',
        correoElectronico: 'rgomez@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'RES-2024/0130',
        firmaDecretoResol: pastDate(550),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: null,
        diasRestantes: 290,
    },
    {
        id: 13,
        pais: 'Reino Unido', paisId: 12,
        fuerza: 'Armada Argentina', fuerzaCodigo: 'ARA', fuerzaId: 2,
        grado: 'Capitán de Navío', gradoAbreviatura: 'CPNV', gradoId: 6,
        cargo: 'Agregado de Defensa',
        apellidoNombre: 'PERALTA, Nicolás Esteban',
        fechaSalida: pastDate(400),
        finComision: daysFromNow(30),
        telefonoOficial: '(0044-20) 7318-1300',
        direccionOficial: '65 Brook Street, London W1K 4AH',
        correoElectronico: 'nperalta@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'DEC-2024/0078',
        firmaDecretoResol: pastDate(420),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: 'CPFG SILVA, H.',
        diasRestantes: 30,
    },
    {
        id: 14,
        pais: 'Paraguay', paisId: 14,
        fuerza: 'Ejército Argentino', fuerzaCodigo: 'EA', fuerzaId: 1,
        grado: 'Coronel', gradoAbreviatura: 'Cnl', gradoId: 2,
        cargo: 'Agregado de Defensa',
        apellidoNombre: 'RAMÍREZ, Osvaldo Hugo',
        fechaSalida: pastDate(600),
        finComision: daysFromNow(120),
        telefonoOficial: '(00595-21) 212-320',
        direccionOficial: 'España 202, Asunción',
        correoElectronico: 'oramirez@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'DEC-2024/0005',
        firmaDecretoResol: pastDate(620),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: null,
        diasRestantes: 120,
    },
    {
        id: 15,
        pais: 'Bolivia', paisId: 15,
        fuerza: 'Ejército Argentino', fuerzaCodigo: 'EA', fuerzaId: 1,
        grado: 'Teniente Coronel', gradoAbreviatura: 'Tcnl', gradoId: 3,
        cargo: 'Agregado Militar',
        apellidoNombre: 'CASTRO, Hernán Gabriel',
        fechaSalida: pastDate(280),
        finComision: daysFromNow(440),
        telefonoOficial: '(00591-2) 241-7737',
        direccionOficial: 'Calle 12 de Calacoto 8041, La Paz',
        correoElectronico: 'hcastro@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'DEC-2025/0045',
        firmaDecretoResol: pastDate(300),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: null,
        diasRestantes: 440,
    },
    {
        id: 16,
        pais: 'Uruguay', paisId: 16,
        fuerza: 'Armada Argentina', fuerzaCodigo: 'ARA', fuerzaId: 2,
        grado: 'Capitán de Navío', gradoAbreviatura: 'CPNV', gradoId: 6,
        cargo: 'Agregado Naval',
        apellidoNombre: 'VARELA, Sergio Damián',
        fechaSalida: pastDate(350),
        finComision: daysFromNow(380),
        telefonoOficial: '(00598-2) 902-8166',
        direccionOficial: 'Av. Libertador 1468, Montevideo',
        correoElectronico: 'svarela@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'DEC-2025/0023',
        firmaDecretoResol: pastDate(370),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: null,
        diasRestantes: 380,
    },
    {
        id: 17,
        pais: 'Rusia', paisId: 13,
        fuerza: 'Fuerza Aérea Argentina', fuerzaCodigo: 'FAA', fuerzaId: 3,
        grado: 'Comodoro', gradoAbreviatura: 'Com', gradoId: 9,
        cargo: 'Agregado Aeronáutico',
        apellidoNombre: 'MORALES, Adrián Javier',
        fechaSalida: pastDate(380),
        finComision: daysFromNow(340),
        telefonoOficial: '(007-495) 232-9993',
        direccionOficial: 'Bolshaya Ordynka 72, Moscú',
        correoElectronico: 'amorales@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'DEC-2025/0031',
        firmaDecretoResol: pastDate(400),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: null,
        diasRestantes: 340,
    },
    {
        id: 18,
        pais: 'Alemania', paisId: 4,
        fuerza: 'Ejército Argentino', fuerzaCodigo: 'EA', fuerzaId: 1,
        grado: 'Suboficial Principal', gradoAbreviatura: 'SP', gradoId: 5,
        cargo: 'Auxiliar de Agregaduría',
        apellidoNombre: 'MEDINA, Jorge Luis',
        fechaSalida: pastDate(590),
        finComision: daysFromNow(20),
        telefonoOficial: '(00-49-030) 2266-8942',
        direccionOficial: 'Von-der-Heydt-Strabe 2, 10785 Berlin',
        correoElectronico: 'jmedina@fuerzas-armadas.mil.ar',
        nroDecretoResol: 'RES-2023/0215',
        firmaDecretoResol: pastDate(610),
        diasEntreFirmaPartida: 20,
        relevoPasajeCargos: 'SP LUNA, D.',
        diasRestantes: 20,
    },
];

// ===== DEMO USER =====
export const DEMO_USER = {
    username: 'demo',
    password: 'demo',
    rol: 'Admin',
    nombreCompleto: 'Administrador Demo',
    token: 'demo-jwt-token-' + Date.now(),
};
